routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'adm']
    ],
    function () {
        Route::get('/', 'Admin\MainController@index')->name('index');
        Route::post('/upload', 'Admin\MainController@upload')->name('upload');
        Route::group(
            [
                'prefix' => 'category',
                'as' => 'categories.',
            ],
            function () {
                Route::get('/', 'Admin\CategoryController@index')->name('list');
                Route::post('/', 'Admin\CategoryController@store')->name('store');
                Route::get('/create', 'Admin\CategoryController@create')->name('create');
                Route::post('/update/{category}', 'Admin\CategoryController@update')->name('update');
                Route::post('/delete/{category}', 'Admin\CategoryController@destroy')->name('delete');
                Route::get('/{category}', 'Admin\CategoryController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'page',
                'as' => 'pages.',
            ],
            function () {
                Route::get('/', 'Admin\PageController@index')->name('list');
                Route::post('/', 'Admin\PageController@store')->name('store');
                Route::get('/create', 'Admin\PageController@create')->name('create');
                Route::post('/update/{page}', 'Admin\PageController@update')->name('update');
                Route::post('/delete/{page}', 'Admin\PageController@destroy')->name('delete');
                Route::get('/{page}', 'Admin\PageController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'product',
                'as' => 'products.',
            ],
            function () {
                Route::get('/', 'Admin\ProductController@index')->name('list');
                Route::post('/', 'Admin\ProductController@store')->name('store');
                Route::get('/create', 'Admin\ProductController@create')->name('create');
                Route::post('/update/{product}', 'Admin\ProductController@update')->name('update');
                Route::post('/delete/{product}', 'Admin\ProductController@destroy')->name('delete');
                Route::get('/comment/{product}/delete/{comment}', 'Admin\ProductController@deleteComment')->name(
                    'comment.delete'
                );
                Route::get('/{product}', 'Admin\ProductController@edit')->name('edit');
            }
        );


        Route::group(
            [
                'prefix' => 'menu',
                'as' => 'menu.',
            ],
            function () {
                Route::get('/', 'Admin\MenuController@index')->name('list');
                Route::post('/', 'Admin\MenuController@store')->name('store');
                Route::get('/create', 'Admin\MenuController@create')->name('create');
                Route::post('/update/{menu}', 'Admin\MenuController@update')->name('update');
                Route::post('/delete/{menu}', 'Admin\MenuController@destroy')->name('delete');
                Route::get('/{menu}', 'Admin\MenuController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'users',
                'as' => 'users.',
            ],
            function () {
                Route::get('/', 'Admin\UserController@index')->name('index');
                Route::get('/set/{user]', 'Admin\UserController@setAdmin')->name('set');
                Route::get('/unset/{user]', 'Admin\UserController@unsetAdmin')->name('unset');
                Route::get('/inset/{user]', 'Admin\UserController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'config',
                'as' => 'config.',
            ],
            function () {
                Route::get('/', 'Admin\ConfigController@index')->name('list');
                Route::post('/', 'Admin\ConfigController@store')->name('store');
                Route::get('/create', 'Admin\ConfigController@create')->name('create');
                Route::post('/update/{cfg}', 'Admin\ConfigController@update')->name('update');
                Route::post('/delete/{cfg}', 'Admin\ConfigController@destroy')->name('delete');
                Route::get('/{cfg}', 'Admin\ConfigController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'promocodes',
                'as' => 'promocodes.',
            ],
            function () {
                Route::get('/', 'Admin\PromoCodeController@index')->name('list');
                Route::post('/', 'Admin\PromoCodeController@store')->name('store');
                Route::get('/create', 'Admin\PromoCodeController@create')->name('create');
                Route::post('/update/{promoCode}', 'Admin\PromoCodeController@update')->name('update');
                Route::post('/delete/{promoCode}', 'Admin\PromoCodeController@destroy')->name('delete');
                Route::get('/{promoCode}', 'Admin\PromoCodeController@edit')->name('edit');
            }
        );
    }
);

Route::group(
    ['as' => 'public.'],
    function () {
        Route::get('/', 'Pub\PageController@home')->name('home');

        Route::group(
            ['as' => 'product.', 'prefix' => 'products'],
            function () {
                Route::get('/', 'Pub\ProductController@index')->name('list');
                Route::get('/{product}', 'Pub\ProductController@show')->name('show');
                Route::post('/comment/{product}/add', 'Pub\ProductController@addComment')->name('comment.add');
            }
        );

        Route::group(
            ['as' => 'cart.', 'prefix' => 'cart'],
            function () {
                Route::get('/', 'Pub\CartController@index')->name('index');
                Route::get('/checkout', 'Pub\CartController@checkout')->name('checkout');
                Route::get('/add/{product}', 'Pub\CartController@add')->name('add');
                Route::post('/add/{product}', 'Pub\CartController@add')->name('add_qty');
                Route::get('/delete/{itemId}', 'Pub\CartController@delete')->name('delete');
                Route::get('/remove/all', 'Pub\CartController@removeAll')->name('remove.all');
                Route::get('/remove/{itemId}', 'Pub\CartController@removeItem')->name('remove.item');
                Route::post('/update', 'Pub\CartController@updateCart')->name('update');
                Route::post('/promocode/activate', 'Pub\CartController@activateCode')->name('promocode.activate');
                Route::post('/promocode/deactivate', 'Pub\CartController@deactivateCode')->name('promocode.deactivate');
            }
        );

        Route::group(
            ['as' => 'payment.', 'prefix' => 'payment'],
            function () {
                Route::get('/success', 'Pub\CartController@success')->name('success');
                Route::get('/cancel', 'Pub\CartController@cancel')->name('cancel');
                Route::get('/bank', 'Pub\CartController@bankPay')->name('bank');
            }
        );

        Route::group(
            ['as' => 'account.', 'prefix' => 'account'],
            function () {
                Route::get('/', 'Pub\AccountController@account')->name('account');
                Route::post('/approve', 'Pub\AccountController@approve')->name('approve');
                Route::post('/add', 'Pub\AccountController@add')->name('add');
                Route::post('/verify', 'Pub\AccountController@verify')->name('verify');
                Route::get('/clear', 'Pub\AccountController@clear')->name('clear');
            }
        );

        Route::get('/{page}', 'Pub\PageController@show')->name('page');
    }
);

app/Http/Controllers/Pub/CartController.php
<?php


namespace App\Http\Controllers\Pub;

use App\Http\Controllers\Controller;
use App\Model\Config;
use App\Model\Product;
use App\Model\PromoCode;
use Cookie;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Overtrue\LaravelShoppingCart\Facade as Cart;
use Overtrue\LaravelShoppingCart\Item;
use Stripe\Charge;
use Stripe\Checkout\Session;
use Stripe\Exception\ApiErrorException;

class CartController extends Controller
{
    public function add(Request $request, Product $product): RedirectResponse
    {
        $cartProduct = Cart::get($product->id);
        if ($cartProduct === null) {
            Cart::add(
                $product->id,
                $product->title,
                $request->get('quantity') ?? 1,
                $product->priceWithAllDiscount(),
            );
        } else {
            Cart::update(
                $product->id,
                $request->get('quantity') ?? 1
            );
        }

        return back();
    }

    public function removeItem(Request $request, string $itemId): RedirectResponse
    {
        $cartProduct = Cart::get($itemId);
        if (($cartProduct->qty === 0 || $request->get('quantity') === 0) && $cartProduct !== null) {
            $this->delete($itemId);
        }

        Cart::update(
            $itemId,
            $cartProduct->qty - 1
        );

        return back();
    }

    public function delete(string $itemId): RedirectResponse
    {
        Cart::remove($itemId);
        return back();
    }

    public static function getAllCartProducts(): array
    {
        return self::getPreparedCart();
    }

    private static function getPreparedCart(): array
    {
        $items = Cart::all()->all();
        $qty = Cart::count();
        $total = 0;
        $totalWithoutDiscount = 0;

        $productIds = [];
        $cartItems = [];
        /** @var Item $item */
        foreach ($items as &$item) {
            $item = $item->all();
            $cartItems[$item['id']] = $item;
            $productIds[] = $item['id'];
        }

        $products = [];
        foreach (Product::find($productIds) as $product) {
            $products[$product->id] = $product;
            $total += $cartItems[$product->id]['qty'] * $product->priceWithAllDiscount();
            $totalWithoutDiscount += $cartItems[$product->id]['qty'] * $product->price;
        }

        return [
            'items' => $items,
            'qty' => $qty,
            'total' => $total,
            'products' => $products,
            'total_without_discount' => $totalWithoutDiscount
        ];
    }

    public function index(): Response
    {
        $title = Config::getValue('cart_title');
        return $this->doResponse('furns.pages.cart.index', compact('title'));
    }

    public function removeAll(): RedirectResponse
    {
        Cart::clean();
        return back();
    }

    /**
     * @throws ApiErrorException
     */
    public function checkout(): Response
    {
        $url = env('APP_URL');
        $lineItems = [];
        $sessionId = '';
        $cart = self::getPreparedCart();

        foreach ($cart['items'] as $cartItem) {
            $product = Product::find($cartItem['id']);
            $lineItems[] = [
                'price_data' => [
                    'currency' => 'usd',
                    'product_data' => [
                        'name' => $cartItem['name'],
                    ],
                    'unit_amount' => $product->priceWithAllDiscount() * 100,
                ],
                'quantity' => $cartItem['qty'],
            ];
        }

        if ($lineItems !== []) {
            $session = Session::create(
                [
                    'payment_method_types' => ['card'],
                    'line_items' => $lineItems,
                    'mode' => 'payment',
                    'success_url' => $url . '/payment/success?session_id={CHECKOUT_SESSION_ID}',
                    'cancel_url' => $url . '/payment/cancel',
                ]
            );

            $sessionId = $session->id;
        }
        $title = Config::getValue('cart_title');
        $stripePk = env('STRIPE_PUBLIC_KEY');
        return $this->doResponse('furns.pages.cart.checkout', compact('sessionId', 'stripePk', 'title'));
    }

    public function success(Request $request): Response
    {
        $status = 'Success';
        Cart::clean();
        $response = json_encode($request->all());
        return $this->doResponse('furns.pages.cart.payment', compact('status', 'response'));
    }

    public function cancel(Request $request): Response
    {
        $status = 'Operation cancelled by payment';
        $response = json_encode($request->all());
        return $this->doResponse('furns.pages.cart.payment', compact('status', 'response'));
    }

    public function bankPay(): RedirectResponse
    {
        $cart = self::getPreparedCart();
        $valet = Auth::user()->getValet();
        try {
            $obj = Charge::create(
                [
                    'amount' => $cart['total'] * 100,
                    'currency' => 'usd',
                    'customer' => $valet->getCusToken(),
                ]
            );

            return response()->redirectToRoute('public.payment.success', ['obj' => $obj->toArray()]);
        } catch (Exception $e) {
            return response()->redirectToRoute('public.payment.cancel', ['message' => $e->getMessage()]);
        }
    }

    public function updateCart(Request $request): RedirectResponse
    {
        $items = Cart::all()->all();

        foreach ($items as $item) {
            $item = $item->all();
            if ($qty = $request->get('product-' . $item['id'])) {
                Cart::update(
                    $item['__raw_id'],
                    $qty
                );
            }
        }

        return back();
    }

    public function activateCode(Request $request): RedirectResponse
    {
        $code = PromoCode::where('code', '=', $request->get("code"))->first();
        $response = back();
        if ($code) {
            return $response->withCookie(cookie('discount', $code->discount))->withCookie(cookie('code', $code->code));
        }
        return $response;
    }

    public function deactivateCode(): RedirectResponse
    {
        Cookie::queue(Cookie::forget('discount'));
        Cookie::queue(Cookie::forget('code'));
        return back();
    }
}

resources/views/furns/pages/cart/index.blade.php
@extends('layouts.furns')

@section('content')
    @if($cart['qty'] === 0)
        <!-- Cart area start -->
        <div class="empty-cart-area pb-100px pt-100px">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="cart-heading">
                            <h2>Your cart item</h2>
                        </div>
                        <div class="empty-text-contant text-center">
                            <i class="icon-handbag"></i>
                            <h1>There are no more items in your cart</h1>
                            <a class="empty-cart-btn" href="{{route('public.product.list')}}">
                                <i class="ion-ios-arrow-left"> </i> Continue shopping
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart area end -->
    @else
        <!-- Cart Area Start -->
        <div class="cart-main-area pt-100px pb-100px"a>
            <div class="container">
                <h3 class="cart-page-title">Your cart items</h3>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        {!! Form::open(['url' => route('public.cart.update'), 'method'=>'POST','enctype'=>'multipart/form-data']) !!}
                        <div class="table-content table-responsive cart-table-content">
                            <table>
                                <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Until Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($cart['items'] as $item)
                                    @php
                                        $product = $cart['products'][$item['id']];
                                    @endphp
                                    <tr>
                                        <td class="product-thumbnail">
                                            <a href="{{route('public.product.show', $product->id)}}"><img
                                                    class="img-responsive ml-3" src="{{$product->photo[0]}}"
                                                    alt=""/></a>
                                        </td>
                                        <td class="product-name"><a href="#">{{$product->title}}</a></td>
                                        <td class="product-price-cart">
                                            @if($product->priceWithAllDiscount() !== $product->price)
                                                <span>${{sprintf("%.2f", $product->priceWithAllDiscount())}}</span>
                                                <span
                                                    style="text-decoration: line-through;color: #999;">${{sprintf("%.2f", $product->price)}}</span>
                                            @else
                                                <span>${{sprintf("%.2f", $product->price)}}</span>
                                            @endif
                                        </td>
                                        <td class="product-quantity">
                                            <div class="cart-plus-minus">
                                                <input class="cart-plus-minus-box" type="text"
                                                       name="product-{{$product->id}}" value="{{$item['qty']}}"/>
                                            </div>
                                        </td>
                                        <td class="product-subtotal">
                                            <span>${{sprintf("%.2f", $product->priceWithAllDiscount() * $item['qty'])}}</span>
                                        <td class="product-remove">
                                            <a href="{{route('public.cart.delete', $item['__raw_id'])}}"><i
                                                    class="icon-close"></i></a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="cart-shiping-update-wrapper">
                                    <div class="cart-shiping-update">
                                        <a href="{{route('public.product.list')}}">Continue Shopping</a>
                                    </div>
                                    <div class="cart-clear">
                                        {!! Form::button('Update Shopping Cart', ['type'=>'submit']) !!}
                                        <a href="{{route('public.cart.remove.all')}}">Clear Shopping Cart</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {!! Form::close() !!}
                        <div class="row">
                            @php
                                $coupon = Cookie::get('code', '');
                                $discount = Cookie::get('discount', 0)
                            @endphp
                            <div class="col-lg-4 col-md-6 mb-lm-30px">
                            </div>
                            <div class="col-lg-4 col-md-6 mb-lm-30px">
                                <div class="discount-code-wrapper">
                                    <div class="title-wrap">
                                        <h4 class="cart-bottom-title section-bg-gray">Use Coupon Code</h4>
                                    </div>
                                    <div class="discount-code">
                                        @if($coupon !== '')
                                            <p>Your coupon code - <b>{{$coupon}}</b></p>
                                            {!! Form::open(['url' => route('public.cart.promocode.deactivate'), 'enctype'=>'multipart/form-data']) !!}
                                            {!! Form::button('Clear coupon', ['type'=>'submit', 'class' => 'cart-btn-2']) !!}
                                            {!! Form::close() !!}
                                        @else
                                            <p>Enter your coupon code if you have one.</p>
                                            {!! Form::open(['url' => route('public.cart.promocode.activate'), 'method'=>'POST','enctype'=>'multipart/form-data']) !!}
                                            <input type="text" required="" name="code"/>
                                            {!! Form::button('Apply Coupon', ['type'=>'submit', 'class' => 'cart-btn-2']) !!}
                                            {!! Form::close() !!}
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-12 mt-md-30px">
                                <div class="grand-totall">
                                    <div class="title-wrap">
                                        <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                                    </div>
                                    <h5>Total products
                                        <span>${{sprintf("%.2f", $cart['total_without_discount'])}}</span>
                                    </h5>

                                    <div class="total-shipping">
                                        @if($coupon !== '')
                                            <h5>Used coupon <b> {{$coupon}} </b><span>{{$discount}}%</span>
                                            </h5>
                                        @endif
                                        <br>
                                        <h5>All discount
                                            <span>${{sprintf("%.2f",$cart['total_without_discount'] - $cart['total'])}}</span>
                                        </h5>
                                    </div>
                                    <h4 class="grand-totall-title">Grand Total
                                        <span>${{sprintf("%.2f", $cart['total'])}}</span></h4>
                                    <a href="{{route('public.cart.checkout')}}">Proceed to Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart Area End -->
    @endif
@endsection

resources/views/furns/pages/cart/payment.blade.php
@extends('layouts.furns')
@section('content')
    <section id="cart" class="padding">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="col-sm-6 col-sm-offset-3">
                        <h2 class="heading_space uppercase">{{$status}}</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script')
    <script>
        console.log(JSON.parse('{!!$response!!}'))
    </script>
@endsection