routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'adm']
    ],
    function () {
        Route::get('/', 'Admin\MainController@index')->name('index');
        Route::post('/upload', 'Admin\MainController@upload')->name('upload');
        Route::group(
            [
                'prefix' => 'category',
                'as' => 'categories.',
            ],
            function () {
                Route::get('/', 'Admin\CategoryController@index')->name('list');
                Route::post('/', 'Admin\CategoryController@store')->name('store');
                Route::get('/create', 'Admin\CategoryController@create')->name('create');
                Route::post('/update/{category}', 'Admin\CategoryController@update')->name('update');
                Route::post('/delete/{category}', 'Admin\CategoryController@destroy')->name('delete');
                Route::get('/{category}', 'Admin\CategoryController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'page',
                'as' => 'pages.',
            ],
            function () {
                Route::get('/', 'Admin\PageController@index')->name('list');
                Route::post('/', 'Admin\PageController@store')->name('store');
                Route::get('/create', 'Admin\PageController@create')->name('create');
                Route::post('/update/{page}', 'Admin\PageController@update')->name('update');
                Route::post('/delete/{page}', 'Admin\PageController@destroy')->name('delete');
                Route::get('/{page}', 'Admin\PageController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'product',
                'as' => 'products.',
            ],
            function () {
                Route::get('/', 'Admin\ProductController@index')->name('list');
                Route::post('/', 'Admin\ProductController@store')->name('store');
                Route::get('/create', 'Admin\ProductController@create')->name('create');
                Route::post('/update/{product}', 'Admin\ProductController@update')->name('update');
                Route::post('/delete/{product}', 'Admin\ProductController@destroy')->name('delete');
                Route::get('/comment/{product}/delete/{comment}', 'Admin\ProductController@deleteComment')->name(
                    'comment.delete'
                );
                Route::get('/{product}', 'Admin\ProductController@edit')->name('edit');
            }
        );


        Route::group(
            [
                'prefix' => 'menu',
                'as' => 'menu.',
            ],
            function () {
                Route::get('/', 'Admin\MenuController@index')->name('list');
                Route::post('/', 'Admin\MenuController@store')->name('store');
                Route::get('/create', 'Admin\MenuController@create')->name('create');
                Route::post('/update/{menu}', 'Admin\MenuController@update')->name('update');
                Route::post('/delete/{menu}', 'Admin\MenuController@destroy')->name('delete');
                Route::get('/{menu}', 'Admin\MenuController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'users',
                'as' => 'users.',
            ],
            function () {
                Route::get('/', 'Admin\UserController@index')->name('index');
                Route::get('/set/{user]', 'Admin\UserController@setAdmin')->name('set');
                Route::get('/unset/{user]', 'Admin\UserController@unsetAdmin')->name('unset');
                Route::get('/inset/{user]', 'Admin\UserController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'config',
                'as' => 'config.',
            ],
            function () {
                Route::get('/', 'Admin\ConfigController@index')->name('list');
                Route::post('/', 'Admin\ConfigController@store')->name('store');
                Route::get('/create', 'Admin\ConfigController@create')->name('create');
                Route::post('/update/{cfg}', 'Admin\ConfigController@update')->name('update');
                Route::post('/delete/{cfg}', 'Admin\ConfigController@destroy')->name('delete');
                Route::get('/{cfg}', 'Admin\ConfigController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'promocodes',
                'as' => 'promocodes.',
            ],
            function () {
                Route::get('/', 'Admin\PromoCodeController@index')->name('list');
                Route::post('/', 'Admin\PromoCodeController@store')->name('store');
                Route::get('/create', 'Admin\PromoCodeController@create')->name('create');
                Route::post('/update/{promoCode}', 'Admin\PromoCodeController@update')->name('update');
                Route::post('/delete/{promoCode}', 'Admin\PromoCodeController@destroy')->name('delete');
                Route::get('/{promoCode}', 'Admin\PromoCodeController@edit')->name('edit');
            }
        );
    }
);

Route::group(
    ['as' => 'public.'],
    function () {
        Route::get('/', 'Pub\PageController@home')->name('home');

        Route::group(
            ['as' => 'product.', 'prefix' => 'products'],
            function () {
                Route::get('/', 'Pub\ProductController@index')->name('list');
                Route::get('/{product}', 'Pub\ProductController@show')->name('show');
                Route::post('/comment/{product}/add', 'Pub\ProductController@addComment')->name('comment.add');
            }
        );

        Route::group(
            ['as' => 'cart.', 'prefix' => 'cart'],
            function () {
                Route::get('/', 'Pub\CartController@index')->name('index');
                Route::get('/checkout', 'Pub\CartController@checkout')->name('checkout');
                Route::get('/add/{product}', 'Pub\CartController@add')->name('add');
                Route::post('/add/{product}', 'Pub\CartController@add')->name('add_qty');
                Route::get('/delete/{itemId}', 'Pub\CartController@delete')->name('delete');
                Route::get('/remove/all', 'Pub\CartController@removeAll')->name('remove.all');
                Route::get('/remove/{itemId}', 'Pub\CartController@removeItem')->name('remove.item');
                Route::post('/update', 'Pub\CartController@updateCart')->name('update');
                Route::post('/promocode/activate', 'Pub\CartController@activateCode')->name('promocode.activate');
                Route::post('/promocode/deactivate', 'Pub\CartController@deactivateCode')->name('promocode.deactivate');
            }
        );

        Route::group(
            ['as' => 'payment.', 'prefix' => 'payment'],
            function () {
                Route::get('/success', 'Pub\CartController@success')->name('success');
                Route::get('/cancel', 'Pub\CartController@cancel')->name('cancel');
                Route::get('/bank', 'Pub\CartController@bankPay')->name('bank');
            }
        );

        Route::group(
            ['as' => 'account.', 'prefix' => 'account'],
            function () {
                Route::get('/', 'Pub\AccountController@account')->name('account');
                Route::post('/approve', 'Pub\AccountController@approve')->name('approve');
                Route::post('/add', 'Pub\AccountController@add')->name('add');
                Route::post('/verify', 'Pub\AccountController@verify')->name('verify');
                Route::get('/clear', 'Pub\AccountController@clear')->name('clear');
            }
        );

        Route::get('/{page}', 'Pub\PageController@show')->name('page');
    }
);

app/Http/Controllers/Admin/ConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Config;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ConfigController extends Controller
{
    public function index()
    {
        $title = "Список конфигураций";
        $cfgList = Config::all();

        return $this->doResponse('admin.config.list', compact('cfgList', 'title'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->toArray(),
            [
                'name' => 'required',
                'key' => 'required'
            ]
        );
        if ($validator->fails()) {
            return response()->redirectToRoute('admin.config.create')->withErrors($validator)->withInput();
        }

        $cfg = new Config();

        $cfg->name = $request->get('name');
        $cfg->key = $request->get('key');
        $cfg->value = $request->get('value');

        $cfg->saveOrFail();

        return response()->redirectToRoute('admin.config.list')->with('success', 'Конфигурация успешно добавлена');
    }

    public function edit(Config $cfg)
    {
        $title = "Редактирование конфигурации";
        $cfgList = Config::all();
        return $this->doResponse('admin.config.edit', compact('cfg', 'title', 'cfgList'));
    }

    public function create()
    {
        $title = "Создание конфигурации";
        return $this->doResponse('admin.config.create', compact('title'));
    }

    public function update(Request $request, Config $cfg)
    {
        $validator = Validator::make(
            $request->toArray(),
            [
                'name' => 'required',
                'key' => 'required'
            ]
        );
        if ($validator->fails()) {
            return response()->redirectToRoute('admin.config.edit', $cfg->id)->withErrors(
                $validator
            )->withInput();
        }

        $cfg->name = $request->get('name');
        $cfg->key = $request->get('key');
        $cfg->value = $request->get('value');

        $cfg->saveOrFail();

        return response()->redirectToRoute('admin.config.list')->with(
            'success',
            'Конфигурация успешно отредактирована'
        );
    }

    public function destroy(Config $cfg)
    {
        $cfg->delete();

        return response()->redirectToRoute('admin.config.list')->with('success', 'Конфигурация успешно удалена');
    }
}

resources/views/admin/config/create.blade.php
@extends('admin.template')
@section('content')
    <div class="wrapper container">

        {!! Form::open(['url' => route('admin.config.store'), 'class'=>'form-horizontal', 'method'=>'POST', 'enctype'=>'multipart/form-data']) !!}

        <div class="form-group">

            {!! Form::label('name', 'Название конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('name', old('name'), ['class' => 'form-control','placeholder'=>'Введите название конфигурации'])!!}
            </div>

        </div>

        <div class="form-group">

            {!! Form::label('key', 'Ключ конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('key', old('key'), ['class' => 'form-control','placeholder'=>'Введите ключ конфигурации'])!!}
            </div>

        </div>

        <div class="form-group">

            {!! Form::label('value', 'Значение конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('value', old('value'), ['class' => 'form-control','placeholder'=>'Введите значение конфигурации'])!!}
            </div>

        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
            </div>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/config/edit.blade.php
@extends('admin.template')
@section('content')
    <div class="wrapper container">

        {!! Form::open(['url' => route('admin.config.update', $cfg->id),'class'=>'form-horizontal','method'=>'POST','enctype'=>'multipart/form-data']) !!}


        <div class="form-group">

            {!! Form::hidden('id', $cfg->id) !!}
            {!! Form::label('name', 'Название конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('name', $cfg->name, ['class' => 'form-control','placeholder'=>'Введите название конфигурации'])!!}
            </div>

        </div>

        <div class="form-group">

            {!! Form::label('key', 'Ключ конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('key', $cfg->key, ['class' => 'form-control','placeholder'=>'Введите ключ конфигурации'])!!}
            </div>

        </div>

        <div class="form-group">

            {!! Form::label('value', 'Значение конфигурации', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('value', $cfg->value, ['class' => 'form-control','placeholder'=>'Введите значение конфигурации'])!!}
            </div>

        </div>


        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
            </div>
        </div>


        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/config/list.blade.php
@extends('admin.template')
@section('content')
    <div class="mt-5 container">
        {!! Html::link(route('admin.config.create'),'Новая конфигурация', ['class' => 'btn btn-success']) !!}
        @if($cfgList)
            <div class="table-responsive text-center">
                <table class="mt-5 table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>№ п/п</th>
                        <th>Наименование</th>
                        <th>Ключ</th>
                        <th>Значение</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($cfgList as $cfg)
                        @if(isset($cfg))
                            <tr>

                                <td>{{ $cfg->id }}</td>
                                <td>{!! Html::link(route('admin.config.edit',['cfg' => $cfg->id]),$cfg->name,['alt'=>$cfg->name]) !!}</td>
                                <td>{{ $cfg->key }}</td>
                                <td>{{ $cfg->value }}</td>
                                <td>
                                    {!! Form::open(['url'=>route('admin.config.delete',['cfg' => $cfg->id]), 'class'=>'form-horizontal','method' => 'POST']) !!}
                                    {!! Form::button('Удалить',['class'=>'btn btn-danger','type'=>'submit' ]) !!}

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
@endsection