routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(
    [
        'prefix' => 'admin',
        'as' => 'admin.',
        'middleware' => ['auth', 'adm']
    ],
    function () {
        Route::get('/', 'Admin\MainController@index')->name('index');
        Route::post('/upload', 'Admin\MainController@upload')->name('upload');
        Route::group(
            [
                'prefix' => 'category',
                'as' => 'categories.',
            ],
            function () {
                Route::get('/', 'Admin\CategoryController@index')->name('list');
                Route::post('/', 'Admin\CategoryController@store')->name('store');
                Route::get('/create', 'Admin\CategoryController@create')->name('create');
                Route::post('/update/{category}', 'Admin\CategoryController@update')->name('update');
                Route::post('/delete/{category}', 'Admin\CategoryController@destroy')->name('delete');
                Route::get('/{category}', 'Admin\CategoryController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'page',
                'as' => 'pages.',
            ],
            function () {
                Route::get('/', 'Admin\PageController@index')->name('list');
                Route::post('/', 'Admin\PageController@store')->name('store');
                Route::get('/create', 'Admin\PageController@create')->name('create');
                Route::post('/update/{page}', 'Admin\PageController@update')->name('update');
                Route::post('/delete/{page}', 'Admin\PageController@destroy')->name('delete');
                Route::get('/{page}', 'Admin\PageController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'product',
                'as' => 'products.',
            ],
            function () {
                Route::get('/', 'Admin\ProductController@index')->name('list');
                Route::post('/', 'Admin\ProductController@store')->name('store');
                Route::get('/create', 'Admin\ProductController@create')->name('create');
                Route::post('/update/{product}', 'Admin\ProductController@update')->name('update');
                Route::post('/delete/{product}', 'Admin\ProductController@destroy')->name('delete');
                Route::get('/comment/{product}/delete/{comment}', 'Admin\ProductController@deleteComment')->name(
                    'comment.delete'
                );
                Route::get('/{product}', 'Admin\ProductController@edit')->name('edit');
            }
        );


        Route::group(
            [
                'prefix' => 'menu',
                'as' => 'menu.',
            ],
            function () {
                Route::get('/', 'Admin\MenuController@index')->name('list');
                Route::post('/', 'Admin\MenuController@store')->name('store');
                Route::get('/create', 'Admin\MenuController@create')->name('create');
                Route::post('/update/{menu}', 'Admin\MenuController@update')->name('update');
                Route::post('/delete/{menu}', 'Admin\MenuController@destroy')->name('delete');
                Route::get('/{menu}', 'Admin\MenuController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'users',
                'as' => 'users.',
            ],
            function () {
                Route::get('/', 'Admin\UserController@index')->name('index');
                Route::get('/set/{user]', 'Admin\UserController@setAdmin')->name('set');
                Route::get('/unset/{user]', 'Admin\UserController@unsetAdmin')->name('unset');
                Route::get('/inset/{user]', 'Admin\UserController@delete')->name('delete');
            }
        );

        Route::group(
            [
                'prefix' => 'config',
                'as' => 'config.',
            ],
            function () {
                Route::get('/', 'Admin\ConfigController@index')->name('list');
                Route::post('/', 'Admin\ConfigController@store')->name('store');
                Route::get('/create', 'Admin\ConfigController@create')->name('create');
                Route::post('/update/{cfg}', 'Admin\ConfigController@update')->name('update');
                Route::post('/delete/{cfg}', 'Admin\ConfigController@destroy')->name('delete');
                Route::get('/{cfg}', 'Admin\ConfigController@edit')->name('edit');
            }
        );

        Route::group(
            [
                'prefix' => 'promocodes',
                'as' => 'promocodes.',
            ],
            function () {
                Route::get('/', 'Admin\PromoCodeController@index')->name('list');
                Route::post('/', 'Admin\PromoCodeController@store')->name('store');
                Route::get('/create', 'Admin\PromoCodeController@create')->name('create');
                Route::post('/update/{promoCode}', 'Admin\PromoCodeController@update')->name('update');
                Route::post('/delete/{promoCode}', 'Admin\PromoCodeController@destroy')->name('delete');
                Route::get('/{promoCode}', 'Admin\PromoCodeController@edit')->name('edit');
            }
        );
    }
);

Route::group(
    ['as' => 'public.'],
    function () {
        Route::get('/', 'Pub\PageController@home')->name('home');

        Route::group(
            ['as' => 'product.', 'prefix' => 'products'],
            function () {
                Route::get('/', 'Pub\ProductController@index')->name('list');
                Route::get('/{product}', 'Pub\ProductController@show')->name('show');
                Route::post('/comment/{product}/add', 'Pub\ProductController@addComment')->name('comment.add');
            }
        );

        Route::group(
            ['as' => 'cart.', 'prefix' => 'cart'],
            function () {
                Route::get('/', 'Pub\CartController@index')->name('index');
                Route::get('/checkout', 'Pub\CartController@checkout')->name('checkout');
                Route::get('/add/{product}', 'Pub\CartController@add')->name('add');
                Route::post('/add/{product}', 'Pub\CartController@add')->name('add_qty');
                Route::get('/delete/{itemId}', 'Pub\CartController@delete')->name('delete');
                Route::get('/remove/all', 'Pub\CartController@removeAll')->name('remove.all');
                Route::get('/remove/{itemId}', 'Pub\CartController@removeItem')->name('remove.item');
                Route::post('/update', 'Pub\CartController@updateCart')->name('update');
                Route::post('/promocode/activate', 'Pub\CartController@activateCode')->name('promocode.activate');
                Route::post('/promocode/deactivate', 'Pub\CartController@deactivateCode')->name('promocode.deactivate');
            }
        );

        Route::group(
            ['as' => 'payment.', 'prefix' => 'payment'],
            function () {
                Route::get('/success', 'Pub\CartController@success')->name('success');
                Route::get('/cancel', 'Pub\CartController@cancel')->name('cancel');
                Route::get('/bank', 'Pub\CartController@bankPay')->name('bank');
            }
        );

        Route::group(
            ['as' => 'account.', 'prefix' => 'account'],
            function () {
                Route::get('/', 'Pub\AccountController@account')->name('account');
                Route::post('/approve', 'Pub\AccountController@approve')->name('approve');
                Route::post('/add', 'Pub\AccountController@add')->name('add');
                Route::post('/verify', 'Pub\AccountController@verify')->name('verify');
                Route::get('/clear', 'Pub\AccountController@clear')->name('clear');
            }
        );

        Route::get('/{page}', 'Pub\PageController@show')->name('page');
    }
);

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    public function index()
    {
        $title = "Список категорий";
        $categories = Category::all();

        return $this->doResponse('admin.categories.list', compact('categories', 'title'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->toArray(),
            [
                'category' => 'required'
            ]
        );
        if ($validator->fails()) {
            return response()->redirectToRoute('admin.categories.create')->withErrors($validator)->withInput();
        }

        $category = new Category();

        $category->category = $request->get('category');

        $category->saveOrFail();

        return response()->redirectToRoute('admin.categories.list')->with('success', 'Категория успешно добавлена');
    }

    public function edit(Category $category)
    {
        $title = "Редактирование категории";
        return $this->doResponse('admin.categories.edit', compact('category', 'title'));
    }

    public function create()
    {
        $title = "Создание категории";
        return $this->doResponse('admin.categories.create', compact('title'));
    }

    public function update(Request $request, Category $category)
    {
        $validator = Validator::make(
            $request->toArray(),
            [
                'category' => 'required'
            ]
        );
        if ($validator->fails()) {
            return response()->redirectToRoute('admin.categories.edit', $category->id)->withErrors(
                $validator
            )->withInput();
        }

        $category->category = $request->get('category');

        $category->saveOrFail();

        return response()->redirectToRoute('admin.categories.list')->with(
            'success',
            'Категория успешно отредактирована'
        );
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return response()->redirectToRoute('admin.categories.list')->with('success', 'Категория успешно удалена');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.template')
@section('content')
    <div class="wrapper container">

        {!! Form::open(['url' => route('admin.categories.store'), 'class'=>'form-horizontal', 'method'=>'POST', 'enctype'=>'multipart/form-data']) !!}


        <div class="form-group">

            {!! Form::label('category', 'Название категории', ['class' => 'col-xs-2 control-label'])   !!}
            <div class="col-xs-8">
                {!! Form::text('category', old('category'), ['class' => 'form-control','placeholder'=>'Введите название категории'])!!}
            </div>

        </div>

        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-10">
                {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
            </div>
        </div>


        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.template')
@section('content')
<div class="wrapper container">

    {!! Form::open(['url' => route('admin.categories.update', $category->id),'class'=>'form-horizontal','method'=>'POST','enctype'=>'multipart/form-data']) !!}


    <div class="form-group">
        {!! Form::hidden('id', $category->id) !!}
        {!! Form::label('category','Название категории',['class' => 'col-xs-2 control-label'])   !!}
        <div class="col-xs-8">
            {!! Form::text('category', $category->category,['class' => 'form-control', 'placeholder'=>'Введите название категории'])!!}
        </div>

    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            {!! Form::button('Сохранить', ['class' => 'btn btn-primary','type'=>'submit']) !!}
        </div>
    </div>


    {!! Form::close() !!}
</div>
@endsection

resources/views/admin/categories/list.blade.php
@extends('admin.template')
@section('content')
    <div class="mt-5 container">
        {!! Html::link(route('admin.categories.create'),'Новая категория', ['class' => 'btn btn-success']) !!}
        @if($categories)
            <div class="table-responsive text-center">
                <table class="mt-5 table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>№ п/п</th>
                        <th>Категория</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($categories as $category)
                        @if(isset($category))
                            <tr>

                                <td>{{ $category->id }}</td>
                                <td>{!! Html::link(route('admin.categories.edit',['category'=>$category->id]),$category->category,['alt'=>$category->category]) !!}</td>
                                <td>
                                    {!! Form::open(['url'=>route('admin.categories.delete',['category' => $category->id]), 'class'=>'form-horizontal','method' => 'POST']) !!}
                                    {!! Form::button('Удалить',['class'=>'btn btn-danger','type'=>'submit' ]) !!}

                                    {!! Form::close() !!}
                                </td>
                            </tr>
                        @endif
                    @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
@endsection